export { GET_TYPES_OF_TEAMS_QUERY } from "./getTypesOfTeamsQuery";
export { CREATE_TEAM_MUTATION } from "./creatTeamMutation";
export { ADD_MEMBERS_TO_TEAM_MUTATION } from "./addMembersToTeamMutation";
export { GET_MY_TEAMS_QUERY } from "./getMyTeamsQuery";
export { GET_TEAM_QUERY } from "./getTeamsQuery";
export { GET_MEMBERS_OF_TEAM_QUERY } from "./getMembersOfTeamQuery";
export { DELETE_TEAM_MUTATION } from "./deleteTeamMutation";
export { GET_FRIENDS_CAN_ADD_TO_TEAM } from "./getFriendsCanAddToTeam";
export { LEAVE_TEAM_MUTATION } from "./leaveTeamMutation";
