export { SEARCH_PLAYER_QUERY } from "./searchPlayerQuery";
export { GET_ALL_FRIENDS_QUERY } from "./getAllFriendsQuery";
export { ADD_FRIEND_MUTATION } from "./addFriendMutation";
export { GET_FRIEND_QUERY } from "./getFriendQuery";
export { ACCEPT_FRIEND_MUTATION } from "./acceptFriendMutation";
export { REJECT_FRIEND_MUTATION } from "./rejectFriendMutation";
export { FIND_PLAYER_ON_MAP } from "./findPlayerOnMapQuery";
export { SEARCH_FRIEND_QUERY } from "./searchFriendQuery";
export { GET_FRIENDS_REQUEST_QUERY } from "./getFriendsRequist";
